/**
 * Component registry generator for component isolation.
 *
 * Writes a static import map file into the target app's app directory.
 * The <CodeSurface /> component uses this registry to dynamically load
 * components for the isolation overlay — no route change needed.
 */

import fs from "fs";
import path from "path";

const REGISTRY_FILE = "designtools-registry.ts";

/** Generate the component registry file in the target app's app directory. */
export function generateComponentRegistry(appDir: string): void {
  const projectRoot = path.dirname(appDir);

  // Discover component files so we can generate static imports
  const componentPaths = discoverComponentFiles(projectRoot);

  const registryEntries = componentPaths
    .map((p) => `  "${p}": () => import("@/${p}"),`)
    .join("\n");

  const content = `"use client";
// Auto-generated by @designtools/next-plugin — do not edit

const COMPONENT_REGISTRY: Record<string, () => Promise<any>> = {
${registryEntries}
};

// Self-register on window so CodeSurface can access it without
// passing functions through the RSC serialization boundary.
if (typeof window !== "undefined") {
  (window as any).__DESIGNTOOLS_REGISTRY__ = COMPONENT_REGISTRY;
}
`;

  fs.writeFileSync(path.join(appDir, REGISTRY_FILE), content, "utf-8");

  // Ensure registry file is gitignored
  ensureGitignore(projectRoot);
}

/** Clean up generated registry file. */
export function cleanupComponentRegistry(appDir: string): void {
  const registryPath = path.join(appDir, REGISTRY_FILE);
  try {
    fs.unlinkSync(registryPath);
  } catch {
    // ignore
  }
}

function ensureGitignore(projectRoot: string): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  const entry = "app/designtools-registry.ts";

  try {
    const existing = fs.existsSync(gitignorePath)
      ? fs.readFileSync(gitignorePath, "utf-8")
      : "";
    if (!existing.includes(entry)) {
      fs.appendFileSync(gitignorePath, `\n# Generated by @designtools/next-plugin\n${entry}\n`);
    }
  } catch {
    // ignore if we can't write gitignore
  }
}

/**
 * Scan the project for component .tsx files in known directories.
 * Returns paths like "components/ui/button" (no extension).
 */
function discoverComponentFiles(projectRoot: string): string[] {
  const dirs = ["components/ui", "src/components/ui"];
  for (const dir of dirs) {
    const fullDir = path.join(projectRoot, dir);
    if (fs.existsSync(fullDir)) {
      const files = fs.readdirSync(fullDir);
      return files
        .filter((f) => f.endsWith(".tsx") || f.endsWith(".ts") || f.endsWith(".jsx"))
        .map((f) => `${dir}/${f.replace(/\.(tsx|ts|jsx|js)$/, "")}`);
    }
  }
  return [];
}
