/**
 * Component registry generator for Vite apps.
 * Adapted from packages/next-plugin/src/preview-route.ts.
 * Writes a static import map into the target app's source directory.
 */

import fs from "fs";
import path from "path";

const REGISTRY_FILE = "designtools-registry.ts";

/** Detect whether this is a Remix/React Router app (app/ root with ~/ alias) or standard Vite (src/ root with @/ alias). */
function detectSourceConvention(projectRoot: string): {
  sourceDir: string;
  importAlias: string;
} {
  // Remix / React Router v7 convention: app/root.tsx exists
  if (fs.existsSync(path.join(projectRoot, "app", "root.tsx"))) {
    return { sourceDir: "app", importAlias: "~/" };
  }
  // Default Vite convention
  return { sourceDir: "src", importAlias: "@/" };
}

/** Generate the component registry file in the target app's source directory. */
export function generateComponentRegistry(
  projectRoot: string,
  componentDir?: string
): void {
  const { sourceDir, importAlias } = detectSourceConvention(projectRoot);
  const fullSourceDir = path.join(projectRoot, sourceDir);
  const componentPaths = discoverComponentFiles(projectRoot, componentDir, sourceDir);

  const registryEntries = componentPaths
    .map((p) => {
      // Strip leading sourceDir/ for import alias
      const importPath = p.startsWith(sourceDir + "/") ? p.slice(sourceDir.length + 1) : p;
      return `  "${p}": () => import("${importAlias}${importPath}"),`;
    })
    .join("\n");

  const content = `// Auto-generated by @designtools/vite-plugin — do not edit

const COMPONENT_REGISTRY: Record<string, () => Promise<any>> = {
${registryEntries}
};

if (typeof window !== "undefined") {
  (window as any).__DESIGNTOOLS_REGISTRY__ = COMPONENT_REGISTRY;
}

export function DesigntoolsRegistry() {
  return null;
}
`;

  fs.writeFileSync(path.join(fullSourceDir, REGISTRY_FILE), content, "utf-8");
  ensureGitignore(projectRoot, sourceDir);
}

/** Clean up generated registry file. */
export function cleanupComponentRegistry(projectRoot: string): void {
  const { sourceDir } = detectSourceConvention(projectRoot);
  const registryPath = path.join(projectRoot, sourceDir, REGISTRY_FILE);
  try {
    fs.unlinkSync(registryPath);
  } catch {
    // ignore
  }
}

function ensureGitignore(projectRoot: string, sourceDir: string): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  const entry = `${sourceDir}/designtools-registry.ts`;

  try {
    const existing = fs.existsSync(gitignorePath)
      ? fs.readFileSync(gitignorePath, "utf-8")
      : "";
    if (!existing.includes(entry)) {
      fs.appendFileSync(
        gitignorePath,
        `\n# Generated by @designtools/vite-plugin\n${entry}\n`
      );
    }
  } catch {
    // ignore if we can't write gitignore
  }
}

function discoverComponentFiles(
  projectRoot: string,
  overrideDir?: string,
  sourceDir?: string
): string[] {
  const defaultDirs = [
    "src/components/ui",
    "components/ui",
    "app/components/ui",
  ];
  const dirs = overrideDir ? [overrideDir] : defaultDirs;
  for (const dir of dirs) {
    const fullDir = path.join(projectRoot, dir);
    if (fs.existsSync(fullDir)) {
      const files = fs.readdirSync(fullDir);
      return files
        .filter(
          (f) => f.endsWith(".tsx") || f.endsWith(".ts") || f.endsWith(".jsx")
        )
        .map((f) => `${dir}/${f.replace(/\.(tsx|ts|jsx|js)$/, "")}`);
    }
  }
  return [];
}
